# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190226_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
            preserve_default=False,
        ),
    ]
